In [1]:
import pandas as pd

In [2]:
train_twitter = pd.read_csv('MSC_Twitter_9835_011720_TRAIN.tsv', sep='\t')
valid_twitter = pd.read_csv('MSC_Twitter_9835_011720_VAL.tsv', sep='\t')
train_web = pd.read_csv('MSC_WebMD_12972_1211019_TRAIN.tsv', sep='\t')
valid_web = pd.read_csv('MSC_WebMD_12972_1211019_VAL.tsv', sep='\t')
train_web

,Unnamed: 0,SOURCE_FILE,DRUG,Ease of Use,Effectiveness,Satisfaction,TEXT,label
0,0,reviews_aug07_parsed/10007_000016.txt,Dramamine,2,1,1,First time user dont know if it works or not,0
1,1,reviews_aug07_parsed/1004_000000.txt,Guaifenesin AC,4,3,1,I previously used Cheratussin but was now disp...,1
2,2,reviews_aug07_parsed/10088_000000.txt,Salagen,1,2,1,"I have Sjogren 's , Lupus and asthma . My D...",1
3,3,reviews_aug07_parsed/10088_000008.txt,Salagen,5,4,2,"While it has worked for me , the sweating and ...",0
4,4,reviews_aug07_parsed/10088_000010.txt,Salagen,5,3,1,Prescribed by dentist to counteract dry mouth ...,1
...,...,...,...,...,...,...,...,...
10373,10373,reviews_aug07_parsed/4718_001392.txt,azithromycin,5,1,1,Started this z-pack in 500 mg pills for thrush...,1
10374,10374,reviews_aug07_parsed/4718_001437.txt,Flomax,1,1,1,Been on Flomax almost a year . Worked good ...,0
10375,10375,reviews_aug07_parsed/4718_001447.txt,Flomax,3,2,1,"It works well for my problem , but causes terr...",0
10376,10376,reviews_aug07_parsed/4718_001449.txt,Flomax,1,1,1,problems ejaculating,0
10377,10377,reviews_aug07_parsed/4718_001450.txt,Flomax,1,1,1,I have only taken for 2 days . I have very ...,0

In [5]:
len(train_twitter.label)+len(valid_twitter.label)

7470

In [3]:
train_twitter.label.value_counts()

0    5380
1     518
Name: label, dtype: int64

In [4]:
valid_twitter.label.value_counts()

0    1434
1     138
Name: label, dtype: int64

In [3]:
valid_web

,SOURCE_FILE,DRUG,Ease of Use,Effectiveness,Satisfaction,TEXT,label
0,reviews_aug07_parsed/148996_000069.txt,Xyzal,5,1,1,I have been taking this medication for about a...,0
1,reviews_aug07_parsed/144377_000075.txt,User Reviews and Ratings - ZOSTAVAX PF subcuta...,5,3,1,I was mistakenly given a pediatric chicken pox...,1
2,reviews_aug07_parsed/12127_000122.txt,Zyrtec,5,3,1,"In the beginning , Zyrtec helped a lot . I ...",1
3,reviews_aug07_parsed/152819_000049.txt,Suprep Bowel Prep Kit,5,2,2,I have an undergraduate degree in chemistry . ...,0
4,reviews_aug07_parsed/11188_001575.txt,trazodone,2,1,1,Did not work ! Caused severe symptoms . ...,0
...,...,...,...,...,...,...,...
1292,reviews_aug07_parsed/251_002591.txt,fluoxetine,4,2,2,Works but side effect might be constipation ?,0
1293,reviews_aug07_parsed/14403_000789.txt,clonazepam,3,3,1,"People , be very careful with this med ! My...",1
1294,reviews_aug07_parsed/12156_000000.txt,User Reviews and Ratings - Depo-Provera intram...,4,4,1,im 30 years old and i 've been on depo for 15 ...,1
1295,reviews_aug07_parsed/14208_000943.txt,gabapentin,3,1,1,Had a stroke and he left side is very numb and...,0
1296,reviews_aug07_parsed/148393_000103.txt,User Reviews and Ratings - Symbicort inhalation,5,1,1,After I lost my voice on Advair my doctor put ...,1

In [6]:
test_twitter = pd.read_csv('Task3a_Twitter_TEST_With_Decoys.tsv', sep='\t')
test_web = pd.read_csv('Task3b_WebMD_TEST_With_Decoys.tsv', sep='\t')
test_twitter

,tweet_id,user_id,text
0,1076904524420399104,15587953,@cal_gal53 @headdock @cshel0607 @VetsUnitedMar...
1,680880616351596548,2306309993,@camilacabello97 please follow me camila i've ...
2,1288114016666099722,16873644,"Medical advances, or technological advances, o..."
3,1204062216028381191,1203619615072493569,@Graaeme1 Steve looks like he hasnt slept in 1...
4,1247297655971201030,20729667,India Cuts Off U.S. from Nearly Half of Its Hy...
...,...,...,...
15355,1288821535139143684,1128516102160617477,THATS WHAT IVE BEEN SAYING! 👇🏼👇🏼👇🏼👇🏼👇🏼I’m an ...
15356,1288049893618196485,1179434096520507393,@VincentCrypt46 @ViktoryOfLight #Hydroxychloro...
15357,1279156955106422791,1213625201071542272,@JoeBiden While Trump actively touted Hydroxyc...
15358,1091070000771801093,2857059774,school nurse when i visit her on a daily basis...
15359,1102939077731598340,173818416,Drug shortages have been on the rise for sever...

In [12]:
# for index, row in train_web.iterrows():
#     row['Ease of Use'] = str(row['Ease of Use'])
#     row['Effectiveness'] = str(row['Effectiveness'])
#     row['Satisfaction'] = str(row['Satisfaction'])
#     train_web.iloc[index] = row
# type(train_web.Effectiveness[0])

str

In [13]:
# for index, row in valid_web.iterrows():
#     row['Ease of Use'] = str(row['Ease of Use'])
#     row['Effectiveness'] = str(row['Effectiveness'])
#     row['Satisfaction'] = str(row['Satisfaction'])
#     valid_web.iloc[index] = row
# type(valid_web.Effectiveness[0])

str

In [14]:
# for index, row in test_web.iterrows():
#     row['Ease of Use'] = str(row['Ease of Use'])
#     row['Effectiveness'] = str(row['Effectiveness'])
#     row['Satisfaction'] = str(row['Satisfaction'])
#     test_web.iloc[index] = row
# type(test_web.Effectiveness[0])

str

In [16]:
# train_web.to_csv('MSC_WebMD_12972_1211019_TRAIN.tsv', sep='\t')
# valid_web.to_csv('MSC_WebMD_12972_1211019_VAL.tsv', sep='\t')
# test_web.to_csv('Task3b_WebMD_TEST_With_Decoys.tsv', sep='\t')

# 5 fold

In [18]:
merge_df_a = pd.concat([train_twitter,valid_twitter])
merge_df_b = pd.concat([train_web,valid_web])
merge_df_b

,SOURCE_FILE,DRUG,Ease of Use,Effectiveness,Satisfaction,TEXT,label
0,reviews_aug07_parsed/10007_000016.txt,Dramamine,2,1,1,First time user dont know if it works or not,0
1,reviews_aug07_parsed/1004_000000.txt,Guaifenesin AC,4,3,1,I previously used Cheratussin but was now disp...,1
2,reviews_aug07_parsed/10088_000000.txt,Salagen,1,2,1,"I have Sjogren 's , Lupus and asthma . My D...",1
3,reviews_aug07_parsed/10088_000008.txt,Salagen,5,4,2,"While it has worked for me , the sweating and ...",0
4,reviews_aug07_parsed/10088_000010.txt,Salagen,5,3,1,Prescribed by dentist to counteract dry mouth ...,1
...,...,...,...,...,...,...,...
1292,reviews_aug07_parsed/251_002591.txt,fluoxetine,4,2,2,Works but side effect might be constipation ?,0
1293,reviews_aug07_parsed/14403_000789.txt,clonazepam,3,3,1,"People , be very careful with this med ! My...",1
1294,reviews_aug07_parsed/12156_000000.txt,User Reviews and Ratings - Depo-Provera intram...,4,4,1,im 30 years old and i 've been on depo for 15 ...,1
1295,reviews_aug07_parsed/14208_000943.txt,gabapentin,3,1,1,Had a stroke and he left side is very numb and...,0
1296,reviews_aug07_parsed/148393_000103.txt,User Reviews and Ratings - Symbicort inhalation,5,1,1,After I lost my voice on Advair my doctor put ...,1

In [19]:
merge_df_a.to_csv('merge_a.tsv', sep='\t')
merge_df_b.to_csv('merge_b.tsv', sep='\t')

In [20]:
merge_df_a = pd.read_csv('merge_a.tsv', sep='\t')
merge_df_a = merge_df_a.drop('Unnamed: 0',axis=1)
merge_df_b = pd.read_csv('merge_b.tsv', sep='\t')
merge_df_b = merge_df_b.drop('Unnamed: 0',axis=1)
merge_df_a

,tweet_id,user_id,text,created_at,label
0,719590190138986497,580495050,pt said that #generic crestor gave him muscle ...,4/11/2016 12:00:00 AM,0
1,916033047803432960,195840877,@MoorseyL She's home. Got her off the Atorvas...,10/5/2017 12:00:00 AM,1
2,693106700321214464,342415585,RT @_lunnada: @getcha_someTEA Advil pms work,1/29/2016 4:21:29 PM,0
3,495646274235170817,395547842,... @ELLEundateable difference being I managed...,8/2/2014 7:04:15 PM,0
4,507229419786612736,500746277,@cvshealth @cvshealth i guess you can drop pr...,9/3/2014 12:00:00 AM,0
...,...,...,...,...,...
7465,986703972244312067,358519345,@calirozzy @vik1958 Some are better than other...,4/18/2018 12:00:00 AM,1
7466,505746627760386049,2483630634,@gemtechsilencer doubling up on the crestor be...,8/30/2014 12:00:00 AM,1
7467,953797472488312832,825505507708280832,As a heart attack survivor (Sept ‘16) &amp; ex...,1/18/2018 12:00:00 AM,0
7468,497487834031607808,1729746374,3 prozac 1 actos 1 januvia 2 glimepiride 2 lov...,8/7/2014 12:00:00 AM,0
7469,1024817065780236296,2288730030,"I’m trying to get away from all the pills, but...",8/2/2018 12:00:00 AM,0

In [21]:
size = len(merge_df_a.label)
for i in range(5):
    merge_df_a[int(i*0.2*size):int((i+1)*0.2*size)].to_csv('validation_a_{}.tsv'.format(i), sep='\t')
    merge_df_a.drop(list(range(int(i*0.2*size),int((i+1)*0.2*size)))).to_csv('train_a_{}.tsv'.format(i), sep='\t')
    
size = len(merge_df_b.label)
for i in range(5):
    merge_df_b[int(i*0.2*size):int((i+1)*0.2*size)].to_csv('validation_b_{}.tsv'.format(i), sep='\t')
    merge_df_b.drop(list(range(int(i*0.2*size),int((i+1)*0.2*size)))).to_csv('train_b_{}.tsv'.format(i), sep='\t')

# pseudo

In [22]:
a_pred = pd.read_csv('a_result.tsv', sep='\t')
pseudo_a = pd.concat([a_pred,merge_df_a]).sample(frac=1)
pseudo_a

                  tweet_id  label  user_id text created_at
6732   1266955337187373062      0      NaN  NaN        NaN
11720   805919453728952320      0      NaN  NaN        NaN
9381   1314886886910054403      0      NaN  NaN        NaN
14082   936776593812234242      0      NaN  NaN        NaN
12369   999655019602329603      1      NaN  NaN        NaN
...                    ...    ...      ...  ...        ...
3678   1233525004861616133      0      NaN  NaN        NaN
2393   1060269081125945347      0      NaN  NaN        NaN
11975  1296652523181236231      0      NaN  NaN        NaN
12865   995658974870597634      0      NaN  NaN        NaN
4313   1288282780632338437      0      NaN  NaN        NaN

[22830 rows x 5 columns]

In [23]:
pseudo_a.to_csv('pseudo_a.tsv', sep='\t')
pseudo_a = pd.read_csv('pseudo_a.tsv', sep='\t')
pseudo_a = pseudo_a.drop('Unnamed: 0',axis=1)

In [25]:
size = len(pseudo_a.label)
for i in range(5):
    pseudo_a[int(i*0.2*size):int((i+1)*0.2*size)].to_csv('validation_a_{}.tsv'.format(i), sep='\t')
    pseudo_a.drop(list(range(int(i*0.2*size),int((i+1)*0.2*size)))).to_csv('train_a_{}.tsv'.format(i), sep='\t')