In [10]:
import pandas as pd

In [8]:
pd.read_csv('train.tsv', sep='\t').Stance.value_counts()

FAVOR      1346
NONE       1336
AGAINST     874
Name: Stance, dtype: int64

In [6]:
pd.read_csv('train.tsv', sep='\t').Premise.value_counts()

0    2225
1    1331
Name: Premise, dtype: int64

In [2]:
df = pd.read_csv('validation.tsv', sep='\t')

In [11]:
pd.read_csv('train.tsv', sep='\t')

,id,Tweet,Claim,Stance,Premise
0,3054935,@realDonaldTrump It's too dangerous to hold th...,school closures,FAVOR,1
1,453444,If masks are so important why is the public no...,face masks,AGAINST,1
2,211600,But if schools close who is gonna occupy those...,school closures,FAVOR,1
3,3049718,@GavinNewsom be the Governor I thought you wer...,stay at home orders,FAVOR,1
4,5039679580998,@BBCNews 1. You are reporting 78% uptake on ma...,face masks,FAVOR,1
...,...,...,...,...,...
3551,333323,@BremainInSpain #lockdown is a #lifechoice for...,stay at home orders,FAVOR,1
3552,910360,The next fucking asshole that tells me there i...,school closures,FAVOR,1
3553,769878,Learning should be constant...then . Why not i...,school closures,FAVOR,1
3554,648731,Every lockdown has had One Common Clause “Esse...,school closures,AGAINST,1
3555,245949,@DrZweliMkhize Don’t teachers and learners fal...,school closures,FAVOR,1

In [4]:
df.Stance.value_counts()

FAVOR      244
NONE       198
AGAINST    158
Name: Stance, dtype: int64

In [3]:
df.Premise.value_counts()

0    380
1    220
Name: Premise, dtype: int64

In [3]:
df

,Unnamed: 0,id,Tweet,Claim,Stance,Premise
0,0,7212131785749,Ordered a mask that had a cute chain attached ...,face masks,FAVOR,0
1,1,2367433035,Who is ready for some #baseball? #BaseballisB...,stay at home orders,NONE,0
2,2,496011,"@Mystere07623203 @va_shiva @Liberty13046 130,0...",face masks,FAVOR,1
3,3,1490686,When they ask me what I did with my life I wil...,face masks,FAVOR,0
4,4,1209366,Taylor not putting her album in physical store...,stay at home orders,FAVOR,0
...,...,...,...,...,...,...
595,595,2949472,@BrianKempGA is one of the few #Governors that...,face masks,AGAINST,1
596,596,208269,I tested positive for Covid. Got it from a fri...,face masks,FAVOR,1
597,597,2316008,"If you are under retirement age, you have a *m...",stay at home orders,AGAINST,1
598,598,659269,@TheLalasventure @doqholliday @realDonaldTrump...,face masks,FAVOR,0
599,599,1940282,@Caissie Obviously I was simply practicing my ...,face masks,FAVOR,0

In [57]:
for i in range(len(df.Tweet)):
    if type(df.Tweet[i]) != str:
        df.Tweet[i] = '0'

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [58]:
df.to_csv('validation_1.tsv', sep='\t')

In [59]:
df1 = pd.read_csv('validation_1.tsv', sep='\t')

In [60]:
df1 = df1.drop('Unnamed: 0',axis=1)

In [61]:
df1

,id,Tweet,Claim,Stance,Premise
0,7212131785749,Ordered a mask that had a cute chain attached ...,face masks,FAVOR,0
1,2367433035,Who is ready for some #baseball? #BaseballisB...,stay at home orders,NONE,0
2,496011,"@Mystere07623203 @va_shiva @Liberty13046 130,0...",face masks,FAVOR,1
3,1490686,When they ask me what I did with my life I wil...,face masks,FAVOR,0
4,1209366,Taylor not putting her album in physical store...,stay at home orders,FAVOR,0
...,...,...,...,...,...
595,2949472,@BrianKempGA is one of the few #Governors that...,face masks,AGAINST,1
596,208269,I tested positive for Covid. Got it from a fri...,face masks,FAVOR,1
597,2316008,"If you are under retirement age, you have a *m...",stay at home orders,AGAINST,1
598,659269,@TheLalasventure @doqholliday @realDonaldTrump...,face masks,FAVOR,0
599,1940282,@Caissie Obviously I was simply practicing my ...,face masks,FAVOR,0

In [62]:
df1.Tweet[204]

'0'

In [6]:
ids = []
claims = []
texts = []

with open('test_origin.tsv','r') as f:
    for item in f.readlines():
        item = item.strip('\n')
        item_list = item.split('\t')
        assert len(item_list)==3
        ids.append(item_list[0])
        claims.append(item_list[1])
        texts.append(item_list[2])

In [7]:
test_df = pd.DataFrame({'id':ids[1:],
                       'claim':claims[1:],
                        'text':texts[1:]
                       })
test_df

,id,claim,text
0,1307558525371965442,school closures,@narendramodi @rajnathsingh Student ka bhi soa...
1,1247739239879467009,stay at home orders,—échale un vistazo a esto… … a fair piece on...
2,1242046510155653125,stay at home orders,Why do think skilling women and girls is impor...
3,1358446499949084675,school closures,To reduce the risk of the virus spreading as e...
4,1249740062775902208,stay at home orders,I speak for a great many people when i say WE ...
...,...,...,...
9995,1242516037628813314,stay at home orders,StayAtHomeSaveLives 21daysLockdown StayAtHome ...
9996,1242746919933415424,stay at home orders,If this is true this is heartbreaking StayAtHo...
9997,1276638598813679617,stay at home orders,"855 Sunset Cove Dr, Winter Haven, FL 33880 3 B..."
9998,1243504288661270528,stay at home orders,StayAtHomeSaveLives StayHomeStaySafe StayHome ...
9999,1237875841981247488,school closures,We’re on track to be like Italy is now. Time t...

In [8]:
for i in range(len(test_df.text)):
    if type(test_df.text[i]) != str:
        print(i)

In [9]:
test_df.to_csv('test.tsv', sep='\t')

In [10]:
pd.read_csv('test.tsv', sep='\t')

,Unnamed: 0,id,claim,text
0,0,1307558525371965442,school closures,@narendramodi @rajnathsingh Student ka bhi soa...
1,1,1247739239879467009,stay at home orders,—échale un vistazo a esto… … a fair piece on...
2,2,1242046510155653125,stay at home orders,Why do think skilling women and girls is impor...
3,3,1358446499949084675,school closures,To reduce the risk of the virus spreading as e...
4,4,1249740062775902208,stay at home orders,I speak for a great many people when i say WE ...
...,...,...,...,...
9995,9995,1242516037628813314,stay at home orders,StayAtHomeSaveLives 21daysLockdown StayAtHome ...
9996,9996,1242746919933415424,stay at home orders,If this is true this is heartbreaking StayAtHo...
9997,9997,1276638598813679617,stay at home orders,"855 Sunset Cove Dr, Winter Haven, FL 33880 3 B..."
9998,9998,1243504288661270528,stay at home orders,StayAtHomeSaveLives StayHomeStaySafe StayHome ...
9999,9999,1237875841981247488,school closures,We’re on track to be like Italy is now. Time t...

# 5 fold

In [5]:
df_val

,Unnamed: 0,id,Tweet,Claim,Stance,Premise
0,0,7212131785749,Ordered a mask that had a cute chain attached ...,face masks,FAVOR,0
1,1,2367433035,Who is ready for some #baseball? #BaseballisB...,stay at home orders,NONE,0
2,2,496011,"@Mystere07623203 @va_shiva @Liberty13046 130,0...",face masks,FAVOR,1
3,3,1490686,When they ask me what I did with my life I wil...,face masks,FAVOR,0
4,4,1209366,Taylor not putting her album in physical store...,stay at home orders,FAVOR,0
...,...,...,...,...,...,...
595,595,2949472,@BrianKempGA is one of the few #Governors that...,face masks,AGAINST,1
596,596,208269,I tested positive for Covid. Got it from a fri...,face masks,FAVOR,1
597,597,2316008,"If you are under retirement age, you have a *m...",stay at home orders,AGAINST,1
598,598,659269,@TheLalasventure @doqholliday @realDonaldTrump...,face masks,FAVOR,0
599,599,1940282,@Caissie Obviously I was simply practicing my ...,face masks,FAVOR,0

In [7]:
df_train = pd.read_csv('train.tsv', sep='\t')
df_val = pd.read_csv('validation.tsv', sep='\t')
merge_df = pd.concat([df_train,df_val.drop('Unnamed: 0',axis=1)])
merge_df

,id,Tweet,Claim,Stance,Premise
0,3054935,@realDonaldTrump It's too dangerous to hold th...,school closures,FAVOR,1
1,453444,If masks are so important why is the public no...,face masks,AGAINST,1
2,211600,But if schools close who is gonna occupy those...,school closures,FAVOR,1
3,3049718,@GavinNewsom be the Governor I thought you wer...,stay at home orders,FAVOR,1
4,5039679580998,@BBCNews 1. You are reporting 78% uptake on ma...,face masks,FAVOR,1
...,...,...,...,...,...
595,2949472,@BrianKempGA is one of the few #Governors that...,face masks,AGAINST,1
596,208269,I tested positive for Covid. Got it from a fri...,face masks,FAVOR,1
597,2316008,"If you are under retirement age, you have a *m...",stay at home orders,AGAINST,1
598,659269,@TheLalasventure @doqholliday @realDonaldTrump...,face masks,FAVOR,0
599,1940282,@Caissie Obviously I was simply practicing my ...,face masks,FAVOR,0

In [8]:
merge_df.to_csv('merge.tsv', sep='\t')

In [4]:
merge_df = pd.read_csv('merge.tsv', sep='\t')
merge_df = merge_df.drop('Unnamed: 0',axis=1)
merge_df

,id,Tweet,Claim,Stance,Premise
0,3054935,@realDonaldTrump It's too dangerous to hold th...,school closures,FAVOR,1
1,453444,If masks are so important why is the public no...,face masks,AGAINST,1
2,211600,But if schools close who is gonna occupy those...,school closures,FAVOR,1
3,3049718,@GavinNewsom be the Governor I thought you wer...,stay at home orders,FAVOR,1
4,5039679580998,@BBCNews 1. You are reporting 78% uptake on ma...,face masks,FAVOR,1
...,...,...,...,...,...
4151,2949472,@BrianKempGA is one of the few #Governors that...,face masks,AGAINST,1
4152,208269,I tested positive for Covid. Got it from a fri...,face masks,FAVOR,1
4153,2316008,"If you are under retirement age, you have a *m...",stay at home orders,AGAINST,1
4154,659269,@TheLalasventure @doqholliday @realDonaldTrump...,face masks,FAVOR,0
4155,1940282,@Caissie Obviously I was simply practicing my ...,face masks,FAVOR,0

In [23]:
size = len(merge_df.id)
for i in range(5):
    merge_df[int(i*0.2*size):int((i+1)*0.2*size)].to_csv('validation_{}.tsv'.format(i), sep='\t')
    merge_df.drop(list(range(int(i*0.2*size),int((i+1)*0.2*size)))).to_csv('train_{}.tsv'.format(i), sep='\t')

# pseudo

In [5]:
stance_pred = pd.read_csv('stance_result.tsv', sep='\t')
premise_pred = pd.read_csv('premise_result.tsv', sep='\t')
pseudo = pd.concat([stance_pred,premise_pred.Premise],axis=1)
train_df = pd.read_csv('train.tsv', sep='\t')
pseudo = pd.concat([train_df,pseudo.rename(columns={'text':'Tweet'})])
df_val = pd.read_csv('validation.tsv', sep='\t')
pseudo_df = pd.concat([pseudo,df_val.drop('Unnamed: 0',axis=1)])
pseudo_df.to_csv('pseudo.tsv', sep='\t')

In [13]:
pseudo_df = pd.read_csv('pseudo.tsv', sep='\t')
pseudo_df = pseudo_df.drop('Unnamed: 0',axis=1)
pseudo_df

,id,Tweet,Claim,Stance,Premise
0,3054935,@realDonaldTrump It's too dangerous to hold th...,school closures,FAVOR,1
1,453444,If masks are so important why is the public no...,face masks,AGAINST,1
2,211600,But if schools close who is gonna occupy those...,school closures,FAVOR,1
3,3049718,@GavinNewsom be the Governor I thought you wer...,stay at home orders,FAVOR,1
4,5039679580998,@BBCNews 1. You are reporting 78% uptake on ma...,face masks,FAVOR,1
...,...,...,...,...,...
14151,2949472,@BrianKempGA is one of the few #Governors that...,face masks,AGAINST,1
14152,208269,I tested positive for Covid. Got it from a fri...,face masks,FAVOR,1
14153,2316008,"If you are under retirement age, you have a *m...",stay at home orders,AGAINST,1
14154,659269,@TheLalasventure @doqholliday @realDonaldTrump...,face masks,FAVOR,0
14155,1940282,@Caissie Obviously I was simply practicing my ...,face masks,FAVOR,0

In [14]:
size = len(pseudo_df.id)
for i in range(5):
    pseudo_df[int(i*0.2*size):int((i+1)*0.2*size)].to_csv('validation_{}.tsv'.format(i), sep='\t')
    pseudo_df.drop(list(range(int(i*0.2*size),int((i+1)*0.2*size)))).to_csv('train_{}.tsv'.format(i), sep='\t')